version: '3.8'

services:
  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: qima_db
      MYSQL_USER: qima
      MYSQL_PASSWORD: qima123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: